#! /usr/bin/python2

#Created by John Ambrose

from Tkinter import *

class Application(Tk):
	storage_needed = 0
	read_ops = 0
	write_ops = 0
	data_scan = 0
	data_return = 0

	def __init__(self, *args, **kwargs):
		Tk.__init__(self, *args, **kwargs)
		#setup frame
		container = Frame(self)
		container.pack(side="top", fill="both", expand=True)
		container.grid_rowconfigure(0, weight=1)
		container.grid_columnconfigure(0, weight=1)

		self.frames = {}

		#puts all the frames in a nice container.
		for F in (StartPage, StoragePage, ComputingPage):
			frame = F(container, self)
			self.frames[F] = frame
			frame.grid(row=0, column=0, sticky="nsew")

		#Starts the application at the correct home page
		self.show_frame(StartPage)

	#need a function for this so a button can change pages
	def show_frame(self, context):
		frame = self.frames[context]
		frame.tkraise()

class StartPage(Frame):
	def __init__(self, parent, controller):
		Frame.__init__(self, parent)

		label = Label(self, text="Welcome to the Cloud Pricing App\nYou Can Compare Between Amazon, Google, and the University of Michigan\nPlease Make A Selection Below", font=("Helvetica", 16, "bold"))
		label.pack(padx=10, pady=10)

		storage_page = Button(self, text="Explore Storage Pricing", padx=10, pady=10, command= lambda: controller.show_frame(StoragePage) )
		storage_page.pack()

		compute_page = Button(self, text="Explore Computing Pricing", padx=10, pady=10, command= lambda: controller.show_frame(ComputingPage) )
		compute_page.pack()

#each page is a seperate class with specific functions.
class StoragePage(Frame):
	def __init__(self, parent, controller):
		Frame.__init__(self, parent)
		self.par_controller = controller

		self.label1 = Label(self, text="Storgae Needed (GB)")
		self.label1.pack()
		self.entry1 = Entry(self)
		self.entry1.pack()

		self.label2 = Label(self, text="Read Operations (10,000)")
		self.label2.pack()
		self.entry2 = Entry(self)
		self.entry2.pack()

		self.label3 = Label(self, text="Write Operations (10,000)")
		self.label3.pack()
		self.entry3 = Entry(self)
		self.entry3.pack()

		self.label4 = Label(self, text="Data Scanned (GB)")
		self.label4.pack()
		self.entry4 = Entry(self)
		self.entry4.pack()

		self.label5 = Label(self, text="Data Returned (GB)")
		self.label5.pack()
		self.entry5 = Entry(self)
		self.entry5.pack()

		self.calc_button = Button(self, text="Calculate Final Cost", padx=10, pady=10, command=self.get_input )
		self.calc_button.pack()

	#Takes all the text entry input and puts them into variables
	def get_input(self):
		Application.storage_needed = float(self.entry1.get() )
		Application.read_ops = float(self.entry2.get() )
		Application.write_ops = float(self.entry3.get() )
		Application.data_scan = float(self.entry4.get() )
		Application.data_return = float(self.entry5.get() )

		print("In get input ", Application.storage_needed)

		#Show final frame to display the calculations
		#self.par_controller.show_frame(PriceStorage)
		self.entry1.pack_forget()
		self.label1.pack_forget()
		self.entry2.pack_forget()
		self.label2.pack_forget()
		self.entry3.pack_forget()
		self.label3.pack_forget()
		self.entry4.pack_forget()
		self.label4.pack_forget()
		self.entry5.pack_forget()
		self.label5.pack_forget()
		self.calc_button.pack_forget()

		label = Label(self, text="This is the price page")
		label.pack()

		self.am_s3 = 0.023 * Application.storage_needed + 0.0007 * Application.data_return + 0.002 * Application.data_scan + 0.05 * Application.write_ops + 0.004 * Application.read_ops

		label2 = Label(self, text="Amazon Pricing (per month)")
		label2.pack()

		label3 = Label(self, text="S3 = $" + str(self.am_s3) )
		label3.pack()



class ComputingPage(Frame):
	def __init__(self, parent, controller):
		Frame.__init__(self, parent)

		label = Label(self, text="Specifications Needed")
		label.pack(padx=10, pady=10)

app = Application()
#app.master.title('Cloud Cost Comparison')
app.mainloop()
