#! /usr/bin/python2

#Created by John Ambrose

from Tkinter import *

class Application(Tk):
	def __init__(self, *args, **kwargs):
		Tk.__init__(self, *args, **kwargs)
		#setup frame
		container = Frame(self)
		container.pack(side="top", fill="both", expand=True)
		container.grid_rowconfigure(0, weight=1)
		container.grid_columnconfigure(0, weight=1)

		self.frames = {}

		#puts all the frames in a nice container.
		for F in (StartPage, StoragePage, ComputingPage):
			frame = F(container, self)
			self.frames[F] = frame
			frame.grid(row=0, column=0, sticky="nsew")

		#Starts the application at the correct home page
		self.show_frame(StartPage)

	#need a function for this so a button can change pages
	def show_frame(self, context):
		frame = self.frames[context]
		frame.tkraise()

class StartPage(Frame):
	def __init__(self, parent, controller):
		Frame.__init__(self, parent)

		label = Label(self, text="Welcome to the Cloud Pricing App\nYou Can Compare Between Amazon, Google, and the University of Michigan\nPlease Make A Selection Below", font=("Helvetica", 16, "bold"))
		label.pack(padx=10, pady=10)

		storage_page = Button(self, text="Explore Storage Pricing", padx=10, pady=10, command= lambda: controller.show_frame(StoragePage) )
		storage_page.pack()

		compute_page = Button(self, text="Explore Computing Pricing", padx=10, pady=10, command= lambda: controller.show_frame(ComputingPage) )
		compute_page.pack()

#each page is a seperate class with specific functions.
class StoragePage(Frame):
	def __init__(self, parent, controller):
		Frame.__init__(self, parent)

		label1 = Label(self, text="Storgae Needed (GB)")
		label1.pack()
		self.entry1 = Entry(self)
		self.entry1.pack()

		label2 = Label(self, text="Read Operations (10,000)")
		label2.pack()
		self.entry2 = Entry(self)
		self.entry2.pack()

		label3 = Label(self, text="Write Operations (10,000)")
		label3.pack()
		self.entry3 = Entry(self)
		self.entry3.pack()

		label4 = Label(self, text="Data Scanned (GB)")
		label4.pack()
		self.entry4 = Entry(self)
		self.entry4.pack()

		label5 = Label(self, text="Data Returned (GB)")
		label5.pack()
		self.entry5 = Entry(self)
		self.entry5.pack()

		calc_button = Button(self, text="Calculate Final Cost", padx=10, pady=10, command=self.get_input )
		calc_button.pack()

	#Takes all the text entry input and puts them into variables
	def get_input(self):
		Application.storage_needed = int(self.entry1.get() )
		Application.read_ops = int(self.entry2.get() )
		Application.write_ops = int(self.entry3.get() )
		Application.data_scan = int( self.entry4.get() )
		Application.data_return = int( self.entry5.get() )

class ComputingPage(Frame):
	def __init__(self, parent, controller):
		Frame.__init__(self, parent)

		label = Label(self, text="Specifications Needed")
		label.pack(padx=10, pady=10)

app = Application()
#app.master.title('Cloud Cost Comparison')
app.mainloop()
